version: '3.4'

# Please consult our docs for more info: https://docs.librechat.ai/install/configuration/docker_override.html

# ---------------------------------------------------

services:

  api:
    # image: ghcr.io/danny-avila/librechat:v0.7.1
    # image: ghcr.io/danny-avila/librechat-dev:latest
    # image: librechat
    image: chodak166/librechat:0.7.2-b6837d6fef
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: /app/librechat.yaml
    - ./volumes/api/images:/app/client/public/images
    - ./volumes/api/logs:/app/api/logs

  mongodb:
    image: mongo:7.0.9-jammy
    restart: unless-stopped
    volumes:
      - ./volumes/mongodb/data-node:/data/db

  meilisearch:
    image: getmeili/meilisearch:v1.7.3
    restart: unless-stopped
    volumes:
      - ./volumes/meilsearch/meili_data_v1.7:/meili_data

  vectordb:
    image: ankane/pgvector:v0.5.1
    restart: unless-stopped
    volumes:
      - ./volumes/vectordb/pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:c2dda202162b588c629dde5cd823e001ac5c6200
    restart: unless-stopped

